#!/usr/bin/env python3

red="\033[1;31m"
green="\033[1;32m"
nm="\033[0m"

print()
print(red + "\tPrueba de input" + nm)
print(green + "\tBy: Darth Venom" + nm)
print()
nombre = input("Ingresa tu nombre: ")
edad = input("Ingresa tu edad: ")

try:
    int(edad)
except ValueError:
    print("La edad debe ser un número")
    exit()

if int(edad) >= 18:
    print("\n\nTu nombre es " + nombre + " y eres mayor de edad\n")
else:
    print("\n\nTu nombre es " + nombre + " y eres menor de edad\n")
